# This is a basic workflow to help you get started with Actions

name: analyze-test

on:
  push:
    branches: [ sdk-v3 ]
  pull_request:
    branches: [ sdk-v3 ]

jobs:
  ios-analyze-test:
    runs-on: macOS-latest
    env:
      XC_VERSION: ${{ '11.6' }}
      XC_WORKSPACE: ${{ 'WindowsAzureMessaging/WindowsAzureMessaging.xcodeproj' }}
      XC_SCHEME: ${{ 'WindowsAzureMessaging iOS Framework' }}
    steps:
    - uses: actions/checkout@v2

    - name: Select Xcode
      run: "sudo xcode-select -switch /Applications/Xcode_XC_VERSION.app"

    - name: iOS Analyze
      run: /usr/bin/xcodebuild analyze -workspace "$XC_WORKSPACE" -scheme "$XC_SCHEME" -destination 'platform=iOS Simulator,name=iPhone 11'

    - name: iOS Test
      run: /usr/bin/xcodebuild test -workspace "$XC_WORKSPACE" -scheme "$XC_SCHEME" -destination 'platform=iOS Simulator,name=iPhone 11'
