name: framework-docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-sdk:
    runs-on: macos-latest
    env:
      XC_VERSION: ${{ '12.3' }}
      XC_WORKSPACE: ${{ 'WindowsAzureMessaging.xcworkspace' }}
      XC_SCHEME: ${{ 'All Frameworks' }}
    steps:
    - uses: actions/checkout@v2
      with: 
        submodules: true

    - name: Select Xcode
      run: "sudo xcode-select -switch /Applications/Xcode_$XC_VERSION.app"

    - name: Update Version
      run: |
        version="$(Scripts/framework-version.sh)+$(git rev-parse --short $GITHUB_SHA)"
        echo "Change version to $version"
        Scripts/framework-version.sh "$version"
        
    - name: Print Swift Package
      run: |
        swift --version
        swift package describe

    - name: Install Jazzy
      run: sudo gem install jazzy --no-document
    
    - name: Build
      run: /usr/bin/xcodebuild -workspace "$XC_WORKSPACE" -scheme "$XC_SCHEME" build CODE_SIGNING_ALLOWED=NO

    - name: Archive
      run: Scripts/build-archive.sh
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: WindowsAzureMessaging
        path: WindowsAzureMessaging-SDK-Apple/WindowsAzureMessaging-SDK-Apple*.zip
